#!/usr/bin/env python3
import argparse, tqdm, shutil, os, glob, re
from pathlib import Path


def parse():
  parser = argparse.ArgumentParser(description='Convert risc-v mini traces generated by sby to binary inputs comparable to what is produced by the fuzzer.')
  parser.add_argument('--in', dest='input', help='input folder from symbiyosys', required=True)
  parser.add_argument('--to', help='output folder', required=True)
  parser.add_argument('--overwrite', help='overwrite the output directory', action='store_true')
  args = parser.parse_args()
  return Path(args.input), Path(args.to), args.overwrite

def create_output_dir(to, overwrite: bool):
  if os.path.exists(to):
    if overwrite:
      shutil.rmtree(to)
    else:
      raise RuntimeError(f"{to} already exists. Use `--overwrite` to allow it to be overwritten.")
  os.mkdir(to)

_mem_re = re.compile(r"_mem\[\d+'b([01]+)\] = \d+'b([01]+)")

def find_mem_init(filename) -> dict:
  res = {}
  with open(filename) as ff:
    for line in ff.readlines():
      m = _mem_re.search(line)
      if m is not None:
        addr = int(m.group(1), 2)
        data = int(m.group(2), 2)
        res[addr] = data
  return res

def sparse_mem_to_bin(mem: dict):
  # the simulated memory has 64-bit, i.e. 8-byte data entries
  max_addr = max(mem.keys()) * 8 # max addr in bytes
  # start with all zeros
  out = b'\00' * (max_addr + 8)
  # write to addresses that have non zero values
  for addr, value in mem.items():
    addr = addr * 8
    bbs = value.to_bytes(8, byteorder='little')
    out = out[:addr] + bbs + out[addr+len(bbs):]
  return out

def convert(inp, to):
  assert os.path.isdir(inp)
  files = [inp / f for f in glob.glob("*_tb.v", root_dir=inp)]
  for filename in tqdm.tqdm(files):
    mem = find_mem_init(filename)
    bbs = sparse_mem_to_bin(mem)
    basename = os.path.basename(filename)
    with open(to / (basename + ".bin"), 'wb') as ff:
      ff.write(bbs)

def main():
  inp, to, overwrite = parse()
  create_output_dir(to, overwrite)
  convert(inp, to)


if __name__ == "__main__":
  main()
